-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-01-06 21:17:38 CET
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE adm_radnik (
    zap_sif VARCHAR2(30) NOT NULL,
    zap_ime VARCHAR2(100) NOT NULL,
    zap_prz VARCHAR2(100) NOT NULL,
    zap_adr VARCHAR2(100),
    zap_ulg VARCHAR2(100) NOT NULL,
    kom_mbr VARCHAR2(30) NOT NULL
);

ALTER TABLE adm_radnik ADD CONSTRAINT adm_radnik_pk PRIMARY KEY ( zap_sif,
                                                                  kom_mbr );

CREATE TABLE cini (
    razvojni_tim_tim_sif VARCHAR2(30) NOT NULL,
    projektant_zap_sif   VARCHAR2(30) NOT NULL,
    projektant_kom_mbr   VARCHAR2(30) NOT NULL
);

ALTER TABLE cini
    ADD CONSTRAINT cini_pk PRIMARY KEY ( razvojni_tim_tim_sif,
                                         projektant_zap_sif,
                                         projektant_kom_mbr );

CREATE TABLE deo (
    deo_sif VARCHAR2(30) NOT NULL,
    deo_ser VARCHAR2(30) NOT NULL,
    deo_str NUMBER NOT NULL,
    deo_dom NUMBER NOT NULL
);

ALTER TABLE deo ADD CONSTRAINT deo_pk PRIMARY KEY ( deo_sif );

CREATE TABLE izlaze (
    proizvod_prz_sif       VARCHAR2(30) NOT NULL,
    predstavnistvo_pre_sif VARCHAR2(30) NOT NULL
);

ALTER TABLE izlaze ADD CONSTRAINT izlaze_pk PRIMARY KEY ( proizvod_prz_sif,
                                                          predstavnistvo_pre_sif );

CREATE TABLE komercijalista (
    zap_sif VARCHAR2(30) NOT NULL,
    zap_ime VARCHAR2(100) NOT NULL,
    zap_prz VARCHAR2(100) NOT NULL,
    zap_adr VARCHAR2(100),
    zap_ulg VARCHAR2(100) NOT NULL,
    kom_mbr VARCHAR2(30) NOT NULL
);

ALTER TABLE komercijalista ADD CONSTRAINT komercijalista_pk PRIMARY KEY ( zap_sif,
                                                                          kom_mbr );

CREATE TABLE kompanija (
    kom_mbr VARCHAR2(30) NOT NULL,
    kom_pib VARCHAR2(30),
    kom_naz VARCHAR2(100) NOT NULL,
    kom_adr VARCHAR2(100),
    kom_brz INTEGER
);

ALTER TABLE kompanija ADD CONSTRAINT kompanija_pk PRIMARY KEY ( kom_mbr );

CREATE TABLE kreira (
    razvojni_tim_tim_sif VARCHAR2(30) NOT NULL,
    projekat_prj_sif     VARCHAR2(30) NOT NULL
);

ALTER TABLE kreira ADD CONSTRAINT kreira_pk PRIMARY KEY ( razvojni_tim_tim_sif,
                                                          projekat_prj_sif );

CREATE TABLE kupac (
    kup_mbr VARCHAR2(30) NOT NULL,
    kup_pib VARCHAR2(30) NOT NULL,
    kup_naz VARCHAR2(100) NOT NULL,
    kup_adr VARCHAR2(100),
    kup_dom NUMBER NOT NULL,
    kup_str NUMBER NOT NULL
);

ALTER TABLE kupac ADD CONSTRAINT kupac_pk PRIMARY KEY ( kup_mbr );

CREATE TABLE nabavlja (
    komercijalista_zap_sif VARCHAR2(30) NOT NULL,
    komercijalista_kom_mbr VARCHAR2(30) NOT NULL,
    deo_deo_sif            VARCHAR2(30) NOT NULL
);

ALTER TABLE nabavlja
    ADD CONSTRAINT nabavlja_pk PRIMARY KEY ( komercijalista_zap_sif,
                                             komercijalista_kom_mbr,
                                             deo_deo_sif );

CREATE TABLE narucuje (
    izlaze_prz_sif VARCHAR2(30) NOT NULL,
    izlaze_pre_sif VARCHAR2(30) NOT NULL,
    kupac_kup_mbr  VARCHAR2(30) NOT NULL
);

ALTER TABLE narucuje
    ADD CONSTRAINT narucuje_pk PRIMARY KEY ( izlaze_prz_sif,
                                             izlaze_pre_sif,
                                             kupac_kup_mbr );

CREATE TABLE pogon (
    pgn_sif           VARCHAR2(30) NOT NULL,
    pgn_naz           VARCHAR2(100) NOT NULL,
    pgn_adr           VARCHAR2(100),
    pgn_prv           TIMESTAMP WITH LOCAL TIME ZONE,
    pgn_brl           INTEGER,
    kompanija_kom_mbr VARCHAR2(30) NOT NULL
);

ALTER TABLE pogon ADD CONSTRAINT pogon_pk PRIMARY KEY ( pgn_sif );

CREATE TABLE predstavnistvo (
    pre_sif           VARCHAR2(30) NOT NULL,
    pre_adr           VARCHAR2(100),
    pre_pib           VARCHAR2(30) NOT NULL,
    pre_kon           VARCHAR2(100),
    pre_mbr           VARCHAR2(30) NOT NULL,
    kompanija_kom_mbr VARCHAR2(30) NOT NULL
);

ALTER TABLE predstavnistvo ADD CONSTRAINT predstavnistvo_pk PRIMARY KEY ( pre_sif );

CREATE TABLE proizvod (
    prz_sif       VARCHAR2(30) NOT NULL,
    prz_naz       VARCHAR2(100) NOT NULL,
    prz_dom       NUMBER NOT NULL,
    prz_str       NUMBER NOT NULL,
    pogon_pgn_sif VARCHAR2(30) NOT NULL
);

ALTER TABLE proizvod ADD CONSTRAINT proizvod_pk PRIMARY KEY ( prz_sif );

CREATE TABLE projekat (
    prj_sif VARCHAR2(30) NOT NULL,
    prj_naz VARCHAR2(100) NOT NULL,
    prj_sts VARCHAR2(30)
);

ALTER TABLE projekat
    ADD CHECK ( prj_sts IN ( 'KOMPLETIRAN', 'NEPROFITABILAN', 'ODBIJEN', 'ODLOZEN', 'ODOBREN',
                             'U_SERIJSKOJ_PROIZVODNJI' ) );

ALTER TABLE projekat ADD CONSTRAINT projekat_pk PRIMARY KEY ( prj_sif );

CREATE TABLE projektant (
    zap_sif VARCHAR2(30) NOT NULL,
    zap_ime VARCHAR2(100) NOT NULL,
    zap_prz VARCHAR2(100) NOT NULL,
    zap_adr VARCHAR2(100),
    zap_ulg VARCHAR2(100) NOT NULL,
    kom_mbr VARCHAR2(30) NOT NULL,
    prj_sef NUMBER NOT NULL
);

ALTER TABLE projektant ADD CONSTRAINT projektant_pk PRIMARY KEY ( zap_sif,
                                                                  kom_mbr );

CREATE TABLE radnik (
    zap_sif        VARCHAR2(30) NOT NULL,
    zap_ime        VARCHAR2(100) NOT NULL,
    zap_prz        VARCHAR2(100) NOT NULL,
    zap_adr        VARCHAR2(100),
    zap_ulg        VARCHAR2(100) NOT NULL,
    kom_mbr        VARCHAR2(30) NOT NULL,
    radnik_zap_sif VARCHAR2(30),
    radnik_kom_mbr VARCHAR2(30),
    rad_sef        NUMBER NOT NULL,
    pogon_pgn_sif  VARCHAR2(30) NOT NULL
);

ALTER TABLE radnik ADD CONSTRAINT radnik_pk PRIMARY KEY ( zap_sif,
                                                          kom_mbr );

CREATE TABLE razvojni_tim (
    tim_brc INTEGER,
    tim_sif VARCHAR2(30) NOT NULL
);

ALTER TABLE razvojni_tim ADD CONSTRAINT razvojni_tim_pk PRIMARY KEY ( tim_sif );

CREATE TABLE sklop (
    proizvod_prz_sif  VARCHAR2(30) NOT NULL,
    proizvod_prz_sif1 VARCHAR2(30) NOT NULL
);

ALTER TABLE sklop ADD CONSTRAINT sklop_pk PRIMARY KEY ( proizvod_prz_sif,
                                                        proizvod_prz_sif1 );

CREATE TABLE stavka (
    stv_sif          VARCHAR2(30) NOT NULL,
    stv_kol          INTEGER NOT NULL,
    stv_ozn          VARCHAR2(100) NOT NULL,
    stv_naz          VARCHAR2(100) NOT NULL,
    stv_cen          FLOAT(3) NOT NULL,
    ugovor_ugv_sif   VARCHAR2(30) NOT NULL,
    proizvod_prz_sif VARCHAR2(30) NOT NULL
);

ALTER TABLE stavka ADD CONSTRAINT stavka_pk PRIMARY KEY ( stv_sif );

CREATE TABLE ugovor (
    ugv_sif                VARCHAR2(30) NOT NULL,
    ugv_dat                DATE NOT NULL,
    ugv_brj                INTEGER NOT NULL,
    adm_radnik_zap_sif     VARCHAR2(30) NOT NULL,
    adm_radnik_kom_mbr     VARCHAR2(30) NOT NULL,
    ugv_sts                VARCHAR2(30) NOT NULL,
    predstavnistvo_pre_sif VARCHAR2(30)
);

ALTER TABLE ugovor
    ADD CHECK ( ugv_sts IN ( 'AKTIVAN', 'CEKA_POTPIS', 'ISPUNJEN', 'OBUSTAVLJEN', 'ODBIJEN',
                             'RASKINUT' ) );

ALTER TABLE ugovor ADD CONSTRAINT ugovor_pk PRIMARY KEY ( ugv_sif );

CREATE TABLE ugradjivanje (
    deo_deo_sif      VARCHAR2(30) NOT NULL,
    proizvod_prz_sif VARCHAR2(30) NOT NULL
);

ALTER TABLE ugradjivanje ADD CONSTRAINT ugradjivanje_pk PRIMARY KEY ( deo_deo_sif,
                                                                      proizvod_prz_sif );

CREATE TABLE zaposleni (
    zap_sif           VARCHAR2(30) NOT NULL,
    zap_ime           VARCHAR2(100) NOT NULL,
    zap_prz           VARCHAR2(100) NOT NULL,
    zap_adr           VARCHAR2(100),
    zap_ulg           VARCHAR2(14) NOT NULL,
    kompanija_kom_mbr VARCHAR2(30) NOT NULL
);

ALTER TABLE zaposleni
    ADD CONSTRAINT ch_inh_zaposleni CHECK ( zap_ulg IN ( 'ADM_RADNIK', 'KOMERCIJALISTA', 'PROJEKTANT', 'RADNIK' ) );

ALTER TABLE zaposleni ADD CONSTRAINT zaposleni_pk PRIMARY KEY ( zap_sif,
                                                                kompanija_kom_mbr );

ALTER TABLE adm_radnik
    ADD CONSTRAINT adm_radnik_zaposleni_fk FOREIGN KEY ( zap_sif,
                                                         kom_mbr )
        REFERENCES zaposleni ( zap_sif,
                               kompanija_kom_mbr );

ALTER TABLE cini
    ADD CONSTRAINT cini_projektant_fk FOREIGN KEY ( projektant_zap_sif,
                                                    projektant_kom_mbr )
        REFERENCES projektant ( zap_sif,
                                kom_mbr );

ALTER TABLE cini
    ADD CONSTRAINT cini_razvojni_tim_fk FOREIGN KEY ( razvojni_tim_tim_sif )
        REFERENCES razvojni_tim ( tim_sif );

ALTER TABLE izlaze
    ADD CONSTRAINT izlaze_predstavnistvo_fk FOREIGN KEY ( predstavnistvo_pre_sif )
        REFERENCES predstavnistvo ( pre_sif );

ALTER TABLE izlaze
    ADD CONSTRAINT izlaze_proizvod_fk FOREIGN KEY ( proizvod_prz_sif )
        REFERENCES proizvod ( prz_sif );

ALTER TABLE komercijalista
    ADD CONSTRAINT komercijalista_zaposleni_fk FOREIGN KEY ( zap_sif,
                                                             kom_mbr )
        REFERENCES zaposleni ( zap_sif,
                               kompanija_kom_mbr );

ALTER TABLE kreira
    ADD CONSTRAINT kreira_projekat_fk FOREIGN KEY ( projekat_prj_sif )
        REFERENCES projekat ( prj_sif );

ALTER TABLE kreira
    ADD CONSTRAINT kreira_razvojni_tim_fk FOREIGN KEY ( razvojni_tim_tim_sif )
        REFERENCES razvojni_tim ( tim_sif );

ALTER TABLE nabavlja
    ADD CONSTRAINT nabavlja_deo_fk FOREIGN KEY ( deo_deo_sif )
        REFERENCES deo ( deo_sif );

ALTER TABLE nabavlja
    ADD CONSTRAINT nabavlja_komercijalista_fk FOREIGN KEY ( komercijalista_zap_sif,
                                                            komercijalista_kom_mbr )
        REFERENCES komercijalista ( zap_sif,
                                    kom_mbr );

ALTER TABLE narucuje
    ADD CONSTRAINT narucuje_izlaze_fk FOREIGN KEY ( izlaze_prz_sif,
                                                    izlaze_pre_sif )
        REFERENCES izlaze ( proizvod_prz_sif,
                            predstavnistvo_pre_sif );

ALTER TABLE narucuje
    ADD CONSTRAINT narucuje_kupac_fk FOREIGN KEY ( kupac_kup_mbr )
        REFERENCES kupac ( kup_mbr );

ALTER TABLE pogon
    ADD CONSTRAINT pogon_kompanija_fk FOREIGN KEY ( kompanija_kom_mbr )
        REFERENCES kompanija ( kom_mbr );

ALTER TABLE predstavnistvo
    ADD CONSTRAINT predstavnistvo_kompanija_fk FOREIGN KEY ( kompanija_kom_mbr )
        REFERENCES kompanija ( kom_mbr );

ALTER TABLE proizvod
    ADD CONSTRAINT proizvod_pogon_fk FOREIGN KEY ( pogon_pgn_sif )
        REFERENCES pogon ( pgn_sif );

ALTER TABLE projektant
    ADD CONSTRAINT projektant_zaposleni_fk FOREIGN KEY ( zap_sif,
                                                         kom_mbr )
        REFERENCES zaposleni ( zap_sif,
                               kompanija_kom_mbr );

ALTER TABLE radnik
    ADD CONSTRAINT radnik_pogon_fk FOREIGN KEY ( pogon_pgn_sif )
        REFERENCES pogon ( pgn_sif );

ALTER TABLE radnik
    ADD CONSTRAINT radnik_radnik_fk FOREIGN KEY ( radnik_zap_sif,
                                                  radnik_kom_mbr )
        REFERENCES radnik ( zap_sif,
                            kom_mbr );

ALTER TABLE radnik
    ADD CONSTRAINT radnik_zaposleni_fk FOREIGN KEY ( zap_sif,
                                                     kom_mbr )
        REFERENCES zaposleni ( zap_sif,
                               kompanija_kom_mbr );

ALTER TABLE sklop
    ADD CONSTRAINT sklop_proizvod_fk FOREIGN KEY ( proizvod_prz_sif )
        REFERENCES proizvod ( prz_sif );

ALTER TABLE sklop
    ADD CONSTRAINT sklop_proizvod_fkv1 FOREIGN KEY ( proizvod_prz_sif1 )
        REFERENCES proizvod ( prz_sif );

ALTER TABLE stavka
    ADD CONSTRAINT stavka_proizvod_fk FOREIGN KEY ( proizvod_prz_sif )
        REFERENCES proizvod ( prz_sif );

ALTER TABLE stavka
    ADD CONSTRAINT stavka_ugovor_fk FOREIGN KEY ( ugovor_ugv_sif )
        REFERENCES ugovor ( ugv_sif );

ALTER TABLE ugovor
    ADD CONSTRAINT ugovor_adm_radnik_fk FOREIGN KEY ( adm_radnik_zap_sif,
                                                      adm_radnik_kom_mbr )
        REFERENCES adm_radnik ( zap_sif,
                                kom_mbr );

ALTER TABLE ugovor
    ADD CONSTRAINT ugovor_predstavnistvo_fk FOREIGN KEY ( predstavnistvo_pre_sif )
        REFERENCES predstavnistvo ( pre_sif );

ALTER TABLE ugradjivanje
    ADD CONSTRAINT ugradjivanje_deo_fk FOREIGN KEY ( deo_deo_sif )
        REFERENCES deo ( deo_sif );

ALTER TABLE ugradjivanje
    ADD CONSTRAINT ugradjivanje_proizvod_fk FOREIGN KEY ( proizvod_prz_sif )
        REFERENCES proizvod ( prz_sif );

ALTER TABLE zaposleni
    ADD CONSTRAINT zaposleni_kompanija_fk FOREIGN KEY ( kompanija_kom_mbr )
        REFERENCES kompanija ( kom_mbr );

CREATE OR REPLACE TRIGGER arc_fkarc_1_komercijalista BEFORE
    INSERT OR UPDATE OF zap_sif, kom_mbr ON komercijalista
    FOR EACH ROW
DECLARE
    d VARCHAR2(14);
BEGIN
    SELECT
        a.zap_ulg
    INTO d
    FROM
        zaposleni a
    WHERE
            a.zap_sif = :new.zap_sif
        AND a.kompanija_kom_mbr = :new.kom_mbr;

    IF ( d IS NULL OR d <> 'KOMERCIJALISTA' ) THEN
        raise_application_error(-20223, 'FK KOMERCIJALISTA_Zaposleni_FK in Table KOMERCIJALISTA violates Arc constraint on Table Zaposleni - discriminator column ZAP_ULG doesn''t have value ''KOMERCIJALISTA'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_adm_radnik BEFORE
    INSERT OR UPDATE OF zap_sif, kom_mbr ON adm_radnik
    FOR EACH ROW
DECLARE
    d VARCHAR2(14);
BEGIN
    SELECT
        a.zap_ulg
    INTO d
    FROM
        zaposleni a
    WHERE
            a.zap_sif = :new.zap_sif
        AND a.kompanija_kom_mbr = :new.kom_mbr;

    IF ( d IS NULL OR d <> 'ADM_RADNIK' ) THEN
        raise_application_error(-20223, 'FK ADM_RADNIK_Zaposleni_FK in Table ADM_RADNIK violates Arc constraint on Table Zaposleni - discriminator column ZAP_ULG doesn''t have value ''ADM_RADNIK'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_radnik BEFORE
    INSERT OR UPDATE OF zap_sif, kom_mbr ON radnik
    FOR EACH ROW
DECLARE
    d VARCHAR2(14);
BEGIN
    SELECT
        a.zap_ulg
    INTO d
    FROM
        zaposleni a
    WHERE
            a.zap_sif = :new.zap_sif
        AND a.kompanija_kom_mbr = :new.kom_mbr;

    IF ( d IS NULL OR d <> 'RADNIK' ) THEN
        raise_application_error(-20223, 'FK RADNIK_Zaposleni_FK in Table RADNIK violates Arc constraint on Table Zaposleni - discriminator column ZAP_ULG doesn''t have value ''RADNIK'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_projektant BEFORE
    INSERT OR UPDATE OF zap_sif, kom_mbr ON projektant
    FOR EACH ROW
DECLARE
    d VARCHAR2(14);
BEGIN
    SELECT
        a.zap_ulg
    INTO d
    FROM
        zaposleni a
    WHERE
            a.zap_sif = :new.zap_sif
        AND a.kompanija_kom_mbr = :new.kom_mbr;

    IF ( d IS NULL OR d <> 'PROJEKTANT' ) THEN
        raise_application_error(-20223, 'FK PROJEKTANT_Zaposleni_FK in Table PROJEKTANT violates Arc constraint on Table Zaposleni - discriminator column ZAP_ULG doesn''t have value ''PROJEKTANT'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            22
-- CREATE INDEX                             0
-- ALTER TABLE                             53
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
